### PR TITLE
WIP feat: watchOS/tvOS/visionOS/SwiftUI support

### PR DESCRIPTION
**Pull request by YoloMao**
### PR 内容

- [x] feat: watchOS support (Tracker)
- [x] feat: tvOS support (Autotracker)
- [x] feat: visionOS support (Tracker, spm)
- [ ] feat: visionOS support (Tracker, cocoapods)
- [x] fix: adapt deep link to SwiftUI

### 遗留问题

 - google/protobuf ~~podspec 暂不支持~~ 已支持 visionOS，待发版，见：
   https://github.com/protocolbuffers/protobuf/blob/main/Protobuf.podspec
   https://github.com/protocolbuffers/protobuf/commit/8afaae52d849cd0f2c613d154ed7f283b85be3bd 
   

### 测试重点

- 所有平台支持以及集成方式，参考新增的 Demo 以及[集成文档](https://github.com/growingio/growingio-sdk-docs/pull/288)
- Visit 事件逻辑是否正常，包括前后台切换是否会刷新 session 等等
- 匿名 id 存储是否正常（删除应用再次重装应用，匿名 id 是否是同一个）
- 事件是否能够正常入库、出库（关闭应用再次打开是否会将上次未发送的事件继续发送）
- 当前网络状态是否正常获取（networkState = 4G or WiFi，以及断网时，是否会停止发送事件）
- Pure SwiftUI App 是否能够集成 SDK，且对应平台支持的功能，如 MobileDebugger、DeepLink，是否正常
- SDK 将忽略 watchOS 的网络可达性判断，始终发送请求，对于 watchOS 的网络测试说明，见下方 comment

### CODE REVIEW

**Comment by YoloMao** [comment]
### 备注
**SwiftUI** 建议通过 `UIApplicationDelegateAdaptor` 进而使用 `AppDelegate` 管理生命周期，并在 `application:didFinishLaunchingWithOptions:` 中初始化 SDK，而不是在 `App.init()`（其将导致 `UIApplication` 获取实例为 `nil`）

**Comment by YoloMao** [comment]
- watchOS 测试网络请求时，需使用真机，Simulator 上始终允许底层网络；
> When writing watchOS networking code, test it on a real device; the simulator always allows low-level networking.

- NWPathMonitor 始终返回 unsatisfied 状态；
> watchOS blocks low-level networking outside of these specific circumstances. For example, if a normal app attempts to start an [NWConnection](https://developer.apple.com/documentation/network/nwconnection), that connection will stay in the [.waiting(_:)](https://developer.apple.com/documentation/network/nwconnection/state/waiting) state with an error of ENETDOWN. Similarly, an [NWPathMonitor](https://developer.apple.com/documentation/network/nwpathmonitor) will remain in the [.unsatisfied](https://developer.apple.com/documentation/network/nwpath/status/unsatisfied) state.

- 因为 watchOS 可通过蓝牙/WiFi 将请求代理到 iPhone 上，因此真机上获取到的网络可达性没有意义
> On watchOS specifically, network requests often get proxied by your iPhone, so the watch’s ability to connect to a specific host is irrelevant.

- watchOS 需同时测试开启和关闭匹配的 iPhone 的网络连接 2 种场景，这是由于 watchOS 可通过匹配的 iPhone 进行网络连接
> Also, test your networking code in a wide variety of network environments. Specifically, test it when the paired iPhone is available and when the paired iPhone is not available. The best way to test the latter is to turn off both Wi-Fi and Bluetooth in the Settings app on the iPhone. Do not use Control Center for this. For an explanation of the difference between these two mechanisms, see [Use Bluetooth and Wi-Fi in Control Center](https://support.apple.com/HT208086).

参考：
https://developer.apple.com/documentation/technotes/tn3135-low-level-networking-on-watchos
https://support.apple.com/en-us/HT204562
https://forums.developer.apple.com/forums/thread/729568

**Review by tianhui12 — APPROVED** [review]

**Review by styluo — APPROVED** [review]

**Comment by YoloMao** [comment]
SDK 所依赖的 google protobuf 对 visionOS via Cocoapods 的支持时间尚不明确 (估计是 3.27.0?)，因此 SDK 先通过 SwiftPM 集成方式支持 visionOS

**Comment by YoloMao** [comment]
Cocoapods 集成支持 visionOS 的版本已发布：https://github.com/growingio/growingio-sdk-ios-autotracker/releases/tag/4.3.1

**Pull request merged**
